name: Install Prerequisites on Ubuntu

runs:
  using: composite
  steps:
    - name: Install packages
      run: |
        sudo apt-get update -qq
        sudo apt-get install -yq \
             libboost-dev \
             libboost-filesystem-dev \
             libboost-program-options-dev \
             libgdal-dev \
             libproj-dev \
             libsparsehash-dev
      shell: bash

